appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: WI17Jq5DFXCnGpAskkrW2a3J/EmF0n4HO8y1pLEPLEWF2dlZPmJSBfO67Tsi/c2WCM5MIW3pAOWO9D7hYLgHSGZpsbHi34G7tAmX700gMgLD36TJ0ihJB6wEYWtb+7G+7TIQ+Ijd+wVdvN1NcjJq07lpr7iqS+0IB+rbIpgU8RGfKY8DIt1iFSbDvbEMg0j3devSv7AeTfB4oOsWR2wF6x3k8je1MMoxSGb9gQQephBsF8OKxAqYLZ9OqwvNqj15e5wQsJXR8j/B3T84hvRm9Rmq+gsYAnVp4ZT4eyL9keBWKsPUeOYPxLNLi0PtiCGAn4kxIIKzzRdlXNA8PL3dUwyMwZs5NdDMH51dALEwdH75+D4zzAiyCD3lF3z0ZWx9+22HaVu0LLJMHst9qJkINj0yUM+34Glcv+KugTxKgP61KtxUlxYil6C3ovuuxOwXHnBl7BZvluRxRYpVC3IOwfWvNmz0yTOi+H/Fx9VeVYvNRetPqNXZfkPntMwoha85H1lwocJSN+Ys22/tMMM8xGVn1XH5lGHwpMBqWv4IVnSZ8pieWIPXtiG014ewXFwpE0lWPQFQBfz085Rqf3OK6Z3Goh/OshN78c6lHm6sJE3sxSmM1Kd8+pQas1ZuPAgozQKwWwq8iFJalHKqic/SSTRsuhOKh6d/Rrk6Qn3uVHQ=}
